name: Gitbook_Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
      - 'contents/**'
      - 'INTRO.md'
      - 'SUMMARY.md'
      - 'GLOSSARY.md'
      - 'book.json'
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"
      - name: Cache NPM dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Cache Gitbook
        id: cache-gitbook
        uses: actions/cache@v4
        with:
          path: ~/.gitbook
          key: ${{ runner.OS }}-gitbook-cache
          restore-keys: |
            ${{ runner.OS }}-gitbook-cache
      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install
      - name: Fix file error
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: sed -i '62,64 s/^/\/\/ /' ./node_modules/npm/node_modules/graceful-fs/polyfills.js
      - name: Build
        run: npm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_book
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
